name: CD
on:
  push:
    branches: master
jobs:
  cd:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log into Crates.io
        run: cargo login ${{ secrets.CRATES_ACCESS_TOKEN }}
      - name: Publish
        run: cargo publish
