on:
  push:
    branches: master
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: cargo fmt --check
      - name: Test
        run: cargo test
      - name: Dry-run publish
        run: cargo publish --dry-run
